In [ ]:
myList=[1,2,3,4,5]
myList.append(6)
myList.append(7)
print(myList)


[1, 2, 3, 4, 5, 6, 7]


In [ ]:
newList=[8,9,10]
myList.extend(newList)
print(myList)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
newList=["Hi","Welcome"]
myList.insert(,newList[0])
myList.insert(3,newList[1])
print(myList)

['Hi', 'Hi', 'Hi', 'Welcome', 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
myList.remove("Welcome")
print(myList)


['Hi', 'Hi', 'Hi', 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
import numpy as np
a=np.array([1,2,3,4])
print(np.shape(a))

(4,)


In [ ]:
a=np.array([[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]])
print(np.shape(a))

(2, 3, 3)


In [ ]:
a=np.array([[1,2,3],[1,2,3],[1,2,3]])
print(np.shape(a))

(3, 3)


In [ ]:
a=np.array([[1,2,3],[1,2,3],[1,2,3]])
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
x=np.ones(5)
print(x)

[1. 1. 1. 1. 1.]


In [ ]:
x=np.zeros([5,6])
print(x)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
x=np.random.random((2,5,6))
print(x)

[[[0.24354079 0.09705517 0.75310234 0.71610044 0.20404396 0.10592351]
  [0.07857772 0.21967693 0.00482115 0.20457801 0.18061453 0.49191875]
  [0.92540577 0.99294626 0.15348028 0.85939847 0.66260293 0.50116072]
  [0.70179875 0.81122334 0.83375611 0.06860983 0.96055318 0.98805128]
  [0.6180387  0.97770895 0.84950366 0.76188391 0.25011061 0.16559697]]

 [[0.56722961 0.47070251 0.71788724 0.90793892 0.40250706 0.03658161]
  [0.92924099 0.11897005 0.06942276 0.12151475 0.93031991 0.52425914]
  [0.78892978 0.30523067 0.53998841 0.37126924 0.67767973 0.65657099]
  [0.13872293 0.98029252 0.61240078 0.16197572 0.14306233 0.91708098]
  [0.23243617 0.34001098 0.12262283 0.03856534 0.23315066 0.71427886]]]


In [ ]:
x=np.ones((4,5,6))
print(x)

[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]]


In [ ]:
a=np.full((5,2,3),0)
print(a)

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]


In [ ]:
a=np.eye(3,3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
a=np.arange(10,50,5)
print(a)

[10 15 20 25 30 35 40 45]


In [ ]:
a=np.linspace(0.,1.,num=5)
print(a)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
a=np.linspace(0.,1.,num=4)
print(a)

[0.         0.33333333 0.66666667 1.        ]


In [ ]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
a[1,1]

5

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a[0,1]

2

In [ ]:
a[0:2,0]

array([1, 4])

In [ ]:
a[0:4,1]

array([2, 5])

In [ ]:
a[0,1:3]

array([2, 3])

In [ ]:
a[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [ ]:
np.shape(a)

(2, 3)

In [57]:
a=np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]])
a

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [62]:
a=np.array([1,2,3,4,5,6,7,89])
np.argmax(a)#returns the largest number index

7

In [63]:
a=np.array([1,2,3,4,5,6,7,89])
np.argmin(a)

0

In [64]:
a=np.array([1,2,3,4,5,6,7,89])
np.argsort(a)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [65]:
a=np.array([1,2,3,4,5,6,7,89])
np.argsort(a)[::-1]

array([7, 6, 5, 4, 3, 2, 1, 0])

In [66]:
a=np.array([1,2,3,4,5,6,7,89])
np.where(a>5)[0]

array([5, 6, 7])

In [71]:
a=np.array([1,2,3,4,5,6,7,89])
print(np.where(a>8))

(array([7]),)


In [75]:
a=np.array([1,2,3,4,5,6,7,89])
np.argmin(a)

0

In [76]:
a=np.array([1,2,3,4,5,6,7,89])
np.argmin(a)

0

In [74]:
a=np.array([1,2,3,4,5,6,7,89])
np.sort(a,kind="quicksort")
a

array([ 1,  2,  3,  4,  5,  6,  7, 89])

In [77]:
a=np.array([1,2,3,4,5,6,7,89])
np.sum(a)

117

In [79]:
%%time
a=np.array([1,2,3,4,5,6,7,89])
np.sum(a)

CPU times: user 141 µs, sys: 0 ns, total: 141 µs
Wall time: 145 µs


117

In [80]:
a=np.array([1,2,3,4,5,6,7,89])
np.sqrt(a[7])

9.433981132056603

In [81]:
a=np.array([[1,2],[3,4]])
b=np.array([[1,2],[3,4]])
a.dot(b)


array([[ 7, 10],
       [15, 22]])

In [82]:
np.dot(a,b)

array([[ 7, 10],
       [15, 22]])

In [83]:
a@b


array([[ 7, 10],
       [15, 22]])

In [84]:
a.T

array([[1, 3],
       [2, 4]])

In [85]:
a.reshape(1,4)

array([[1, 2, 3, 4]])

In [88]:
a=a.reshape(4,1)
a

array([[1],
       [2],
       [3],
       [4]])

In [89]:
a=a.squeeze()
a


array([1, 2, 3, 4])

In [91]:
a=a.reshape(-1,1)
a

array([[1],
       [2],
       [3],
       [4]])